language: node_js
node_js:
  - '8'
dist: trusty # A Linux distro
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run build # It also builds the client
script:
  - nohup npm run start &
  - sleep 3 # best practice, give a pause until the server initializes
  - npm run test
